hotels/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import BaseDetailView
from hotels.models import Hotel
from hotels.views import HotelSearchView, HotelUpdate, HotelView, HotelRegisterView, HotelAddImageView, HotelRemoveImage, HotelAddRoomClass, HotelEditRoomClass, HotelRemoveRoomClass, HotelListAdmin, HotelList

hotel_patterns = patterns(
    '',
    url(r'^update/$', HotelUpdate.as_view(), name='hotel_edit'),
    url(r'^update/addImage$', HotelAddImageView.as_view(), name='hotel_add_image'),
    url(r'^update/addRoomClass$', HotelAddRoomClass.as_view(), name='hotel_add_room_class'),
    url(r'^update/editRoomClass/(?P<room_class_pk>\d+)/$', HotelEditRoomClass.as_view(), name='hotel_edit_room_class'),
    url(r'^update/removeRoomClass/(?P<room_class_pk>\d+)/$', HotelRemoveRoomClass.as_view(),
        name='hotel_delete_room_class'),
    url(r'^update/removeImage/(?P<images_pk>\d+)/$', HotelRemoveImage.as_view(), name='hotel_remove_image'),
    url(r'^view/$', HotelView.as_view(), name='hotel_view'),
    # url(r'^data.map/$', GeoJSONLayerView.as_view(model=Hotel), name='data'),
)

urlpatterns = patterns(
    '',
    url(r'^$', HotelList.as_view(), name='hotel_list'),
    url(r'^admin/$', HotelListAdmin.as_view(), name='hotel_list_admin'),
    url(r'^search/$', HotelSearchView.as_view(), name='hotel_search'),
    url(r'^(?P<pk>\d+)/', include(hotel_patterns)),
    url(r'^roomClass/$', (lambda: None), name='hotel_room_class_edit'),
    url(r'^new/$', HotelRegisterView.as_view(), name='hotel_new'),
    url(r'^approve/$', (lambda: None), name='hotel_approve'),
)

simorgh/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
import hotels.urls, accounts.urls, reservation.urls, reports.urls

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'simorgh.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', TemplateView.as_view(template_name='home.html'), name='homepage'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hotels/', include(hotels.urls)),
    url(r'^accounts/', include(accounts.urls)),
    url(r'^reservation/', include(reservation.urls)),
    url(r'^reports/', include(reports.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotels/models.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.db import models
import datetime
from django.db.models.aggregates import Avg
from geoposition import Geoposition
from geoposition.fields import GeopositionField
from werkzeug.exceptions import LengthRequired
from accounts.middleware import get_current_user
from django.db.models import Q


class ApprovedManager(models.Manager):
    def get_queryset(self):
        return super(ApprovedManager, self).get_queryset().filter(Q(is_approved=True) | Q(owner=get_current_user()))


class Hotel(models.Model):
    all = models.Manager()
    objects = ApprovedManager()

    CHOICES_STARS = [(i, i * u'*') for i in range(1, 6)]
    name = models.CharField(max_length=32, verbose_name=u'نام')
    city = models.CharField(max_length=56, blank=True, verbose_name=u'شهر')
    owner = models.ForeignKey('auth.User')
    server_url = models.URLField(blank=True, verbose_name=u'آدرس اینترنتی کارگذار هتل')
    room_count = models.PositiveIntegerField(verbose_name=u'تعداد اتاق‌')
    stars = models.SmallIntegerField(choices=CHOICES_STARS, verbose_name=u'ستاره')
    address = models.TextField(blank=True, verbose_name=u'آدرس')
    is_approved = models.BooleanField(default=False, verbose_name=u'تاییدیه‌ی مدیر')
    features = models.ManyToManyField('hotels.Feature', blank=True, verbose_name=u'ویژگی‌ها')
    main_image = models.ImageField(upload_to='images/', verbose_name=u'تصویر اصلی')
    position = GeopositionField(default=Geoposition(52.522906, 13.41156))

    @property
    def avg_starts(self):
        return self.vote_set().aggregate(Avg('stars')).values()[0]

    def vote_set(self):
        from reservation.models import Vote

        return Vote.objects.filter(reservation_order__room_class__hotel=self)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('hotel_view', kwargs={'pk': self.id})

    def has_edit_permission(self):
        user = get_current_user()
        if not user.is_authenticated():
            return False
        if user.is_superuser:
            return True
        if self.owner_id == user.id:
            return True
        return False


class RoomClass(models.Model):
    hotel = models.ForeignKey('hotels.Hotel', verbose_name=u'هتل')
    name = models.CharField(max_length=32, verbose_name=u'نام')
    description = models.TextField(verbose_name=u'توضیح')
    price = models.PositiveIntegerField(verbose_name=u'قیمت')
    bed_count = models.PositiveIntegerField(verbose_name=u'تعداد تخت‌خواب')
    features = models.ManyToManyField('hotels.Feature', blank=True, verbose_name=u'ویژگی‌ها')

    def __unicode__(self):
        return self.name


class HotelImage(models.Model):
    hotel = models.ForeignKey('hotels.Hotel', verbose_name=u'هتل')
    caption = models.TextField(blank=True, verbose_name=u'زیرنویس عکس')
    image = models.ImageField(upload_to='images/', verbose_name=u'عکس')

    def __unicode__(self):
        return self.caption


class Feature(models.Model):
    name = models.CharField(max_length=128, verbose_name=u'نام')
    icon = models.URLField(verbose_name=u'آدرس عکس')
    is_for_hotel = models.BooleanField(default=True, verbose_name=u'برای هتل')
    is_for_room = models.BooleanField(default=True, verbose_name=u'برای اتاق')

    def __unicode__(self):
        return self.name

hotels/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render_to_response
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, CreateView, ModelFormMixin, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.shortcuts import redirect

from accounts.views import HotelPermissionMixin, SuperUserMixin
from hotels.form import SearchByLocationForm, SearchByNameForm, SearchByVoteForm, RegisterHotelForm, UpdateHotelForm, \
    HotelAddImageForm, HotelAddRoomClass, UpdateRoomClassForm, \
    StatusForm
from hotels.models import Hotel, HotelImage, RoomClass


class HotelList(ListView):
    model = Hotel
    template_name = 'hotels/hotel_list.html'

    def get_context_data(self, **kwargs):
        nameString = self.request.GET.get('name', '')
        locationString = self.request.GET.get('location', '')
        votesValue = self.request.GET.get('votes', -1)

        return {'object_list': filter(Hotel.has_edit_permission,
                                      Hotel.all.filter(name__contains=nameString, city__contains=locationString,
                                                       stars__gt=votesValue))}


class HotelListAdmin(SuperUserMixin, ListView):
    model = Hotel
    template_name = 'hotels/hotel_list_admin.html'

    def get_context_data(self, **kwargs):
        return {'object_list': Hotel.all.filter()}


    def post(self, request, *args, **kwargs):
        list_post = request.POST.getlist('toupdate')
        hotels = Hotel.all.filter()
        for hotel in hotels:
            if hotel.is_approved:
                if list_post.count(str(hotel.id)) == 0:
                    hotel.is_approved = False
                    hotel.save()
            else:
                if list_post.count(str(hotel.id)) != 0:
                    hotel.is_approved = True
                    hotel.save()
        return redirect(reverse_lazy('hotel_list_admin'))


class HotelUpdate(HotelPermissionMixin, UpdateView):
    form_class = UpdateHotelForm
    model = Hotel
    template_name = 'hotels/hotel_edit.html'


class HotelAddImageView(HotelPermissionMixin, CreateView):
    form_class = HotelAddImageForm
    model = HotelImage
    template_name = 'hotels/hotel_add_image.html'
    # success_url = reverse_lazy('hotel_update')

    def form_valid(self, form):
        object = form.save(commit=False)
        object.hotel_id = self.kwargs['pk']
        object.save()
        messages.success(self.request, u'عکس با موفقیت اضافه شد.')
        return redirect(reverse_lazy('hotel_edit', kwargs=self.kwargs))


class HotelRemoveImage(HotelPermissionMixin, DeleteView):
    model = HotelImage

    def get_success_url(self):
        return reverse_lazy('hotel_edit', kwargs={'pk': self.kwargs['pk']})

    def get_object(self, queryset=None):
        messages.info(self.request, u'عکس با موفقیت حذف شد')
        return HotelImage.objects.get(pk=self.kwargs['images_pk'])


class HotelAddRoomClass(HotelPermissionMixin, CreateView):
    model = RoomClass
    form_class = HotelAddRoomClass
    template_name = 'hotels/hotel_add_room_class.html'

    def form_valid(self, form):
        object = form.save(commit=False)
        object.hotel_id = self.kwargs['pk']
        object.save()
        messages.success(self.request, u'کلاس اتاق با موفقیت اضافه شد')
        return redirect(reverse_lazy('hotel_edit', kwargs=self.kwargs))


class HotelEditRoomClass(HotelPermissionMixin, UpdateView):
    model = RoomClass
    form_class = UpdateRoomClassForm
    template_name = 'hotels/hotel_edit_room_class.html'

    def get_success_url(self):
        messages.info(self.request, u'ویرایش کلاس اتاق با موفقیت انجام شد')
        return reverse_lazy('hotel_edit', kwargs={'pk': self.kwargs['pk']})

    def get_object(self, queryset=None):
        return RoomClass.objects.get(pk=self.kwargs['room_class_pk'])


class HotelRemoveRoomClass(HotelPermissionMixin, DeleteView):
    model = RoomClass

    def get_success_url(self):
        return reverse_lazy('hotel_edit', kwargs={'pk': self.kwargs['pk']})

    def get_object(self, queryset=None):
        messages.info(self.request, u'کلاس اتاق با موفقیت حذف شد')
        return RoomClass.objects.get(pk=self.kwargs['room_class_pk'])


class HotelView(HotelPermissionMixin, DetailView):
    model = Hotel
    template_name = 'hotels/hotel_view.html'
    editing = False

    def get_context_data(self, **kwargs):
        ret = super(HotelView, self).get_context_data(**kwargs)
        ret['estelam_form'] = StatusForm()
        return ret


class HotelSearchView(TemplateView):
    template_name = 'hotels/hotel_search.html'

    def get_context_data(self, **kwargs):
        return {
            'location_form': SearchByLocationForm(),
            'name_form': SearchByNameForm(),
            'vote_form': SearchByVoteForm()
        }

    def post(self, request):
        return render_to_response()


class HotelRegisterView(CreateView):
    model = Hotel
    template_name = 'hotels/hotel_register.html'
    form_class = RegisterHotelForm
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        messages.success(self.request, u'هتل جدید با موفقیت ثبت شد، منتظر تایید مدیر سیستم باشید')
        return super(ModelFormMixin, self).form_valid(form)

hotels/templates/hotels/hotel_edit.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load thumbnail %}

{% block content %}
    <script>
        function deleteImage(url) {
            $('<form method="post" action="' + url + '"><input name="csrfmiddlewaretoken" value="{{ csrf_token }}"></form>').
                    appendTo(document.body).submit();
        }
        function deleteRoomClass(url) {
            $('<form method="post" action="' + url + '"><input name="csrfmiddlewaretoken" value="{{ csrf_token }}"></form>').
                    appendTo(document.body).submit();
        }
    </script>
    <div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="post" class="form" name="main-form">
                {{ form.media }}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            تصویرها
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="row">

                            {% for hotelImage in hotel.hotelimage_set.all %}

                                <div class="col-sm-6 col-md-4">
                                    <div class="thumbnail">
                                        <img src="{{ hotelImage.image|thumbnail_url:'avatar' }}"
                                             alt="{{ hotelImage.caption }}">

                                        <div class="caption">
                                            <h6>{{ hotelImage.caption }}</h6>

                                            <a class="btn btn-danger"
                                               onclick="deleteImage('{% url 'hotel_remove_image' pk=hotel.id images_pk=hotelImage.id %}')">
                                                        <span class="glyphicon glyphicon-minus-sign"
                                                              aria-hidden="true"/>
                                                حذف
                                            </a>

                                        </div>
                                    </div>
                                </div>


                            {% endfor %}
                        </div>
                    </div>
                    <div class="panel-footer">
                        {% buttons %}
                            <a href="{% url 'hotel_add_image' pk=hotel.id %}" class="btn btn-success bt-lg">
                                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"/>
                                افزدون عکس
                            </a>
                        {% endbuttons %}
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            کلاس‌های اتاق
                        </div>
                    </div>
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-3">
                                نام
                            </div>
                            <div class="col-md-3">
                                قیمت
                            </div>
                            <div class="col-md-3">
                                تعداد تخت‌خواب
                            </div>
                        </div>

                        {% for roomClass in hotel.roomclass_set.all %}
                            <div class="row">
                                <div class="col-md-3">
                                    {{ roomClass.name }}
                                </div>
                                <div class="col-md-3">
                                    {{ roomClass.price }}
                                </div>
                                <div class="col-md-2">
                                    {{ roomClass.bed_count }}
                                </div>
                                <div class="col-md-4">
                                    <a href="{% url 'hotel_edit_room_class' pk=hotel.id room_class_pk=roomClass.id %}"
                                       class="btn btn-info" role="button">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"/>

                                        ویرایش
                                    </a>
                                    <a onclick="deleteRoomClass('{% url 'hotel_delete_room_class' pk=hotel.id room_class_pk=roomClass.id %}')"
                                       class="btn btn-danger" role="button">
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"/>

                                        حذف
                                    </a>
                                </div>
                            </div>
                            <p>

                            </p>
                        {% endfor %}

                    </div>
                    <div class="panel-footer">
                        {% buttons %}
                            <a href="{% url 'hotel_add_room_class' pk=hotel.id %}" class="btn btn-success bt-lg">
                                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"/>
                                افزودن کلاس اتاق
                            </a>
                        {% endbuttons %}
                    </div>
                </div>

                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %}
                        ارسال
                    </button>
                    <a href="{% url 'homepage' %}" class="btn btn-danger">
                        انصراف
                    </a>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

hotels/templates/hotels/hotel_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load thumbnail %}


{% block content %}
    <div style="padding-top: 30px">
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    لیست هتل‌ها
                </div>
                <table class="table">
                    <p>

                    </p>

                    {% for hotel in object_list %}
                        <div class="row">
                            <div class="col-md-1">

                            </div>
                            <div class="col-md-3 thumbnail">
                                <img class="hotel-image" src="{{ hotel.main_image |thumbnail_url:'avatar' }}">
                            </div>
                            <div class="col-md-3 text-info ">
                                {{ hotel.name }}
                                {% for s in hotel.get_stars_display %}
                                    <img src="http://www.eghamat24.com/images/com/ic_staron.png">
                                {% endfor %}
                                <br/>
                                <br/>
                                <br/>
                                {{ hotel.city }}
                                <br/>
                                <br/>
                                {{ hotel.address }}
                            </div>
                            <div class="col-md-5 text-center">
                                {% buttons %}
                                    <a href="{% url 'hotel_view' pk=hotel.id %}" class="btn {% if hotel.is_approved %} btn-success {% else %} btn-danger {% endif %} bt-lg">
                                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"/>
                                        مشاهده‌ی جزییات
                                    </a>
                                    <br>
                                    {% if not hotel.is_approved %}
                                        <a class="alert-danger">
                                        توجه: هتل تایید نشده است
                                    {% endif %}
                                </a>
                                    <br>
                                    {% if hotel.has_edit_permission %}
                                    <a href="{% url 'hotel_edit' pk=hotel.id %}" class="btn btn-primary" style="margin-top: 15px;">
                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"/>
                                            ویرایش

                                        </a>
                                    {% endif %}
                                {% endbuttons %}
                            </div>
                            <div class="col-md-1">

                            </div>
                        </div>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
{% endblock %}

hotels/templates/hotels/hotel_register.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

hotels/templates/hotels/hotel_view.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load humanize %}

{% block content %}
    <div class="container hotel-view" style="padding-top: 30px">
        <div class="row">
            <div class="col-md-7">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h3>
                                {{ hotel.name }}
                            </h3>
                        </div>
                    </div>
                    <div class="panel-body">
                        <img class="hotel-image" src="{{ MEDIA_URL }}{{ hotel.main_image }}">
                        {% for feature in hotel.features.all %}
                            <span class="label label-success">
                                <img src="{{ feature.icon }}">
                                {{ feature.name }}
                                </span>
                            &nbsp;
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">
                            مشخصات
                        </div>
                    </div>
                    <div class="panel-body">
                        <dl class="dl-horizontal">
                            <dt>
                                تعداد اتاق
                            </dt>
                            <dd>
                                {{ hotel.room_count }}
                            </dd>
                            <dt>
                                کیفیت
                            </dt>
                            <dd>
                                {% for s in hotel.get_stars_display %}
                                    <img src="http://www.eghamat24.com/images/com/ic_staron.png">
                                {% endfor %}
                            </dd>
                            <dt>
                                امتیاز در سایت
                            </dt>
                            <dd>
                                {{ hotel.avg_starts }}
                            </dd>
                            <dt>
                                شهر
                            </dt>
                            <dd>
                                {{ hotel.city }}
                            </dd>
                            <dt>
                                آدرس
                            </dt>
                            <dd>
                                {{ hotel.address }}
                            </dd>
                        </dl>

                        <div id="googleMap" style="width:430px;height:380px;"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>
                                گالری تصاویر
                            </h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                {% for image in hotel.hotelimage_set.all %}
                                    <li data-target="#carousel-example-generic"
                                        data-slide-to="{{ forloop.counter0 }}"
                                            {% if forloop.first %} class="active" {% endif %}></li>
                                {% endfor %}
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner " role="listbox">
                                {% for image in hotel.hotelimage_set.all %}
                                    <div class="item {% if forloop.first %} active {% endif %}">
                                        <img src="{{ image.image.url }}"
                                             style="max-height: 300px; margin: auto">

                                    </div>
                                {% endfor %}
                            </div>

                            <!-- Controls -->
                            <a class="left carousel-control" href="#carousel-example-generic" role="button"
                               data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" role="button"
                               data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>
                                نظرات مسافران
                            </h4>
                        </div>
                    </div>
                    <div class="panel-body" style="height: 330px; overflow-y: auto;">
                        <div class="list-group">
                            {% for vote in hotel.vote_set.all %}
                                <a class="list-group-item">
                                    {% for s in vote.get_stars_display %}
                                        <img src="http://www.eghamat24.com/images/com/ic_staron.png">
                                    {% endfor %}
                                    {{ vote.comment }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% for class in hotel.roomclass_set.all %}
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="panel-title">
                                اتاق‌های
                                {{ class.name }}
                                (
                                {{ class.bed_count }}
                                تخته
                                )
                                <span class="pull-left">
                                    قیمت هر شب:
                                    {{ class.price|intcomma }}
                                     ریال
                                </span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <p>
                                {% for feature in class.features.all %}
                                    <span class="label label-success">
                                    <img src="{{ feature.icon }}">
                                    {{ feature.name }}
                                    </span>
                                    &nbsp;
                                {% endfor %}
                            </p>
                            {{ class.description }}
                        </div>
                        <div class="panel-footer estelam">
                            <div class="row">
                                <form>
                                    <div class="col-md-5">
                                        {% bootstrap_form estelam_form layout='horizontal' %}
                                    </div>
                                    <div class="col-md-1">
                                        <button class="btn btn-default" onclick="getStatus(this)">
                                            استعلام
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <script src="http://maps.googleapis.com/maps/api/js"></script>
    <script>
        var position = new google.maps.LatLng({{ hotel.position.latitude|stringformat:"f" }}, {{ hotel.position.longitude|stringformat:"f" }});
        function initialize() {
            var mapProp = {
                center: position,
                zoom: 15,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
            new google.maps.Marker({
                position: position
            }).setMap(map);
        }
        google.maps.event.addDomListener(window, 'load', initialize);

        function getStatus(button, event) {
            console.log($(button));
            return false;
        }

        if (false) {
            $("#idForm").submit(function () {

                var url = "path/to/your/script.php"; // the script where you handle the form input.

                $.ajax({
                    type: "POST",
                    url: url,
                    data: $("#idForm").serialize(), // serializes the form's elements.
                    success: function (data) {
                        alert(data); // show response from the php script.
                    }
                });

                return false; // avoid to execute the actual submit of the form.
            });
        }
    </script>
{% endblock %}